name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:
  schedule: # execute every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.GITHUB_TOKEN }}, you can change to your personal access token
          GITHUB_TOKEN: ${{ secrets.PROFILE_CARD }}
        with:
          USERNAME: ${{ github.repository_owner }}
